### ISSUE TITLE
Documentation Fix: Tips

### ISSUE THREAD

**Issue by Dumisani21** [Xolani-M/docker-practice#1]
On documentation tips you wrote this:
```
  - To stop the container, press Ctrl + C in the terminal.
  - Or   - To stop the container, press Ctrl + C in the terminal.
  - Or docker stop username/your-app-name
```

The problems is that you can't stop the docker container with the name you used to create the docker image but you
have to use the running docker image name of the docker ID but if you write username/your-app-name
it will say that it did not find the image 
the right way to stop the docker image is to first getting the running container :
```bash
docker ps
```
which will list the running images in this format
| CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES |
|---|---|---|---|---|---|---|
|4e3gg4455235 | username/app:2.0 | "docker-entrypoint.s…" |  About a minute ago | Up 59 seconds |  0.0.0.0:3000->3000/tcp | wizardly_almeida

then from there, you want to select the ID or name

* Using IMAGE ID
```bash
docker stop 4e3gg4455235
```
* Using NAMES
```bash
docker stop wizardly_almeida
```

**Comment by Xolani-M** [comment]
Thank you Dumisani21. The issue is fixed.
